import type { Metadata } from "next";
import { Nav, NavLink } from "./_components/AdminNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <Nav>
        <NavLink href='/admin'>Dashboard</NavLink>
        <NavLink href='/admin/shoes'>Shoes </NavLink>
        <NavLink href='/admin/customers'>Customers</NavLink>
        <NavLink href='/admin/orders'>Orders</NavLink>
      </Nav>
      <div>{children}</div>
    </>
  );
}
