export const shoes = [
  {
    name: "Wayvee Leather",
    price: 4999.0,
    description:
      "A stylish and durable leather shoe designed for comfort and fashion.",
    availableSizes: ["7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Vans",
    category: "Casual",
    images: [
      "/shoes/Vans/Wayvee-Leather/0.webp",
      "/shoes/Vans/Wayvee-Leather/1.webp",
      "/shoes/Vans/Wayvee-Leather/2.webp",
      "/shoes/Vans/Wayvee-Leather/3.webp",
    ],
    id: 1,
  },
  {
    name: "Chukka Push",
    price: 4599.0,
    description:
      "Chukka boots with a modern twist, offering both style and comfort.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Vans",
    category: "Boots",
    images: [
      "/shoes/Vans/Chukka-Push/0.webp",
      "/shoes/Vans/Chukka-Push/1.webp",
      "/shoes/Vans/Chukka-Push/2.webp",
      "/shoes/Vans/Chukka-Push/3.webp",
    ],
    id: 2,
  },
  {
    name: "Knu Skool",
    price: 4999.0,
    description: "Retro-inspired sneakers with a chunky sole and bold design.",
    availableSizes: ["7", "8", "8.5", "9", "9.5", "10", "11", "12"],
    brand: "Vans",
    category: "Sneakers",
    images: [
      "/shoes/Vans/Knu-Skool/0.webp",
      "/shoes/Vans/Knu-Skool/1.webp",
      "/shoes/Vans/Knu-Skool/2.webp",
      "/shoes/Vans/Knu-Skool/3.webp",
    ],
    id: 3,
  },
  {
    name: "Sport Low",
    price: 4399.0,
    description:
      "Low-profile sneakers perfect for everyday wear and casual outings.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Vans",
    category: "Sport",
    images: [
      "/shoes/Vans/Sport-Low/0.webp",
      "/shoes/Vans/Sport-Low/1.webp",
      "/shoes/Vans/Sport-Low/2.webp",
      "/shoes/Vans/Sport-Low/3.webp",
    ],
    id: 4,
  },
  {
    name: "Authentic",
    price: 3999.0,
    description:
      "Classic and versatile sneakers with a simple yet iconic design.",
    availableSizes: ["5", "6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Vans",
    category: "Casual",
    images: [
      "/shoes/Vans/Authentic/0.webp",
      "/shoes/Vans/Authentic/1.webp",
      "/shoes/Vans/Authentic/2.webp",
      "/shoes/Vans/Authentic/3.webp",
    ],
    id: 5,
  },
  {
    name: "Old Skool Primary Check",
    price: 4599.0,
    description:
      "Featuring the iconic Old Skool design with a primary check pattern.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Vans",
    category: "Skate",
    images: [
      "/shoes/Vans/Old-Skool-Primary-Check/0.webp",
      "/shoes/Vans/Old-Skool-Primary-Check/1.webp",
      "/shoes/Vans/Old-Skool-Primary-Check/2.webp",
      "/shoes/Vans/Old-Skool-Primary-Check/3.webp",
    ],
    id: 6,
  },
  {
    name: "Lowland ComfyCush Leather",
    price: 4799.0,
    description:
      "Leather sneakers with ComfyCush technology for extra comfort.",
    availableSizes: ["7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Vans",
    category: "Casual",
    images: [
      "/shoes/Vans/Lowland-ComfyCush-Leather/0.webp",
      "/shoes/Vans/Lowland-ComfyCush-Leather/1.webp",
      "/shoes/Vans/Lowland-ComfyCush-Leather/2.webp",
      "/shoes/Vans/Lowland-ComfyCush-Leather/3.webp",
    ],
    id: 7,
  },
  {
    name: "Classic Slip-On",
    price: 3799.0,
    description: "Slip-on sneakers with a classic design and easy wearability.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Vans",
    category: "Slip-On",
    images: [
      "/shoes/Vans/Classic-Slip-On/0.webp",
      "/shoes/Vans/Classic-Slip-On/1.webp",
      "/shoes/Vans/Classic-Slip-On/2.webp",
      "/shoes/Vans/Classic-Slip-On/3.webp",
    ],
    id: 8,
  },
  {
    name: "Classic Slip-On Checkerboard",
    price: 3899.0,
    description: "Iconic checkerboard slip-on sneakers that stand out.",
    availableSizes: ["5", "6", "7", "8", "8.5", "9"],
    brand: "Vans",
    category: "Slip-On",
    images: [
      "/shoes/Vans/Classic-Slip-On-Checkerboard/0.webp",
      "/shoes/Vans/Classic-Slip-On-Checkerboard/1.webp",
      "/shoes/Vans/Classic-Slip-On-Checkerboard/2.webp",
      "/shoes/Vans/Classic-Slip-On-Checkerboard/3.webp",
    ],
    id: 9,
  },
  {
    name: "Old School",
    price: 4599.0,
    description:
      "A staple in the Vans lineup with classic skate style and design.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Vans",
    category: "Skate",
    images: [
      "/shoes/Vans/Old-School/0.webp",
      "/shoes/Vans/Old-School/1.webp",
      "/shoes/Vans/Old-School/2.webp",
      "/shoes/Vans/Old-School/3.webp",
    ],
    id: 10,
  },
  {
    name: "Gazelle",
    price: 4999.0,
    description:
      "Classic Adidas sneakers known for their timeless design and comfort.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Adidas",
    category: "Casual",
    images: [
      "/shoes/Adidas/Gazelle/0.jpg",
      "/shoes/Adidas/Gazelle/1.jpg",
      "/shoes/Adidas/Gazelle/2.jpg",
      "/shoes/Adidas/Gazelle/3.jpg",
      "/shoes/Adidas/Gazelle/4.jpg",
    ],
    id: 11,
  },
  {
    name: "4DFWD 4",
    price: 8999.0,
    description:
      "High-performance running shoes featuring 4D printed midsoles for superior cushioning.",
    availableSizes: ["7", "8", "8.5", "9", "9.5", "10", "11", "12"],
    brand: "Adidas",
    category: "Running",
    images: [
      "/shoes/Adidas/4DFWD-4/0.jpg",
      "/shoes/Adidas/4DFWD-4/1.jpg",
      "/shoes/Adidas/4DFWD-4/2.jpg",
      "/shoes/Adidas/4DFWD-4/3.jpg",
      "/shoes/Adidas/4DFWD-4/4.jpg",
    ],
    id: 12,
  },
  {
    name: "Own the Game 3",
    price: 4599.0,
    description:
      "Versatile basketball shoes designed for both performance and style on the court.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Adidas",
    category: "Basketball",
    images: [
      "/shoes/Adidas/Own-the-Game-3/0.jpg",
      "/shoes/Adidas/Own-the-Game-3/1.jpg",
      "/shoes/Adidas/Own-the-Game-3/2.jpg",
      "/shoes/Adidas/Own-the-Game-3/3.jpg",
      "/shoes/Adidas/Own-the-Game-3/4.jpg",
    ],
    id: 13,
  },
  {
    name: "SL 72 RS",
    price: 4999.0,
    description:
      "Retro-inspired sneakers with a sleek design and comfortable fit.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Adidas",
    category: "Casual",
    images: [
      "/shoes/Adidas/SL-72-RS/0.jpg",
      "/shoes/Adidas/SL-72-RS/1.jpg",
      "/shoes/Adidas/SL-72-RS/2.jpg",
      "/shoes/Adidas/SL-72-RS/3.jpg",
      "/shoes/Adidas/SL-72-RS/4.jpg",
    ],
    id: 14,
  },
  {
    name: "Stan Smith",
    price: 4299.0,
    description:
      "Iconic tennis shoes known for their minimalist style and classic appeal.",
    availableSizes: ["5", "6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Adidas",
    category: "Casual",
    images: [
      "/shoes/Adidas/Stan-Smith/0.jpg",
      "/shoes/Adidas/Stan-Smith/1.jpg",
      "/shoes/Adidas/Stan-Smith/2.jpg",
      "/shoes/Adidas/Stan-Smith/3.jpg",
      "/shoes/Adidas/Stan-Smith/4.jpg",
    ],
    id: 15,
  },
  {
    name: "Samba OG",
    price: 4799.0,
    description:
      "Classic soccer-inspired sneakers with a retro look and comfortable feel.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Adidas",
    category: "Casual",
    images: [
      "/shoes/Adidas/Samba-OG/0.jpg",
      "/shoes/Adidas/Samba-OG/1.jpg",
      "/shoes/Adidas/Samba-OG/2.jpg",
      "/shoes/Adidas/Samba-OG/3.jpg",
      "/shoes/Adidas/Samba-OG/4.jpg",
    ],
    id: 16,
  },
  {
    name: "Converse x Wonka Chuck 70",
    price: 4999.0,
    description:
      "A limited edition Chuck 70 collaboration with Wonka, featuring unique design elements.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Converse",
    category: "Casual",
    images: [
      "/shoes/Converse/Converse-x-Wonka-Chuck-70/0.jpg",
      "/shoes/Converse/Converse-x-Wonka-Chuck-70/1.jpg",
      "/shoes/Converse/Converse-x-Wonka-Chuck-70/2.jpg",
      "/shoes/Converse/Converse-x-Wonka-Chuck-70/3.jpg",
      "/shoes/Converse/Converse-x-Wonka-Chuck-70/4.jpg",
    ],
    id: 17,
  },
  {
    name: "Weapon",
    price: 4799.0,
    description:
      "Classic basketball-inspired shoes with a retro design and comfortable fit.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Converse",
    category: "Basketball",
    images: [
      "/shoes/Converse/Weapon/0.jpg",
      "/shoes/Converse/Weapon/1.jpg",
      "/shoes/Converse/Weapon/2.jpg",
      "/shoes/Converse/Weapon/3.jpg",
      "/shoes/Converse/Weapon/4.jpg",
    ],
    id: 18,
  },
  {
    name: "Chuck Taylor All Star Cruise",
    price: 4399.0,
    description:
      "A stylish and comfortable version of the iconic Chuck Taylor All Star, designed for everyday wear.",
    availableSizes: ["5", "6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Converse",
    category: "Casual",
    images: [
      "/shoes/Converse/Chuck-Taylor-All-Star-Cruise/0.jpg",
      "/shoes/Converse/Chuck-Taylor-All-Star-Cruise/1.jpg",
      "/shoes/Converse/Chuck-Taylor-All-Star-Cruise/2.jpg",
      "/shoes/Converse/Chuck-Taylor-All-Star-Cruise/3.jpg",
      "/shoes/Converse/Chuck-Taylor-All-Star-Cruise/4.jpg",
    ],
    id: 19,
  },
  {
    name: "Converse x Dungeons and Dragons Chuck 70",
    price: 4999.0,
    description:
      "A special edition Chuck 70 featuring artwork inspired by Dungeons and Dragons.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Converse",
    category: "Casual",
    images: [
      "/shoes/Converse/Converse-x-Dungeons-and-Dragons-Chuck-70/0.jpg",
      "/shoes/Converse/Converse-x-Dungeons-and-Dragons-Chuck-70/1.jpg",
      "/shoes/Converse/Converse-x-Dungeons-and-Dragons-Chuck-70/2.jpg",
      "/shoes/Converse/Converse-x-Dungeons-and-Dragons-Chuck-70/3.jpg",
      "/shoes/Converse/Converse-x-Dungeons-and-Dragons-Chuck-70/4.jpg",
    ],
    id: 20,
  },
  {
    name: "Chuck 70 Monochrome",
    price: 4599.0,
    description:
      "A sleek, all-monochrome version of the Chuck 70 with a minimalist design.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Converse",
    category: "Casual",
    images: [
      "/shoes/Converse/Chuck-70-Monochrome/0.jpg",
      "/shoes/Converse/Chuck-70-Monochrome/1.jpg",
      "/shoes/Converse/Chuck-70-Monochrome/2.jpg",
      "/shoes/Converse/Chuck-70-Monochrome/3.jpg",
      "/shoes/Converse/Chuck-70-Monochrome/4.jpg",
    ],
    id: 21,
  },
  {
    name: "Star Player 76 Premium Canvas",
    price: 4699.0,
    description:
      "Premium canvas sneakers with a vintage look and modern comfort.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Converse",
    category: "Casual",
    images: [
      "/shoes/Converse/Star-Player-76-Premium-Canvas/0.jpg",
      "/shoes/Converse/Star-Player-76-Premium-Canvas/1.jpg",
      "/shoes/Converse/Star-Player-76-Premium-Canvas/2.jpg",
      "/shoes/Converse/Star-Player-76-Premium-Canvas/3.jpg",
      "/shoes/Converse/Star-Player-76-Premium-Canvas/4.jpg",
    ],
    id: 22,
  },
  {
    name: "One Star Academy Pro Suede",
    price: 4799.0,
    description:
      "Suede sneakers with a stylish design and enhanced durability.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Converse",
    category: "Casual",
    images: [
      "/shoes/Converse/One-Star-Academy-Pro-Suede/0.jpg",
      "/shoes/Converse/One-Star-Academy-Pro-Suede/1.jpg",
      "/shoes/Converse/One-Star-Academy-Pro-Suede/2.jpg",
      "/shoes/Converse/One-Star-Academy-Pro-Suede/3.jpg",
      "/shoes/Converse/One-Star-Academy-Pro-Suede/4.jpg",
    ],
    id: 23,
  },
  {
    name: "Star Player 76",
    price: 4399.0,
    description:
      "Classic Star Player sneakers with a retro design and comfortable fit.",
    availableSizes: ["5", "6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Converse",
    category: "Casual",
    images: [
      "/shoes/Converse/Star-Player-76/0.jpg",
      "/shoes/Converse/Star-Player-76/1.jpg",
      "/shoes/Converse/Star-Player-76/2.jpg",
      "/shoes/Converse/Star-Player-76/3.jpg",
      "/shoes/Converse/Star-Player-76/4.jpg",
    ],
    id: 24,
  },
  {
    name: "Chuck Taylor All Star",
    price: 3999.0,
    description:
      "The iconic Chuck Taylor All Star with a classic design and versatile style.",
    availableSizes: ["5", "6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Converse",
    category: "Casual",
    images: [
      "/shoes/Converse/Chuck-Taylor-All-Star/0.jpg",
      "/shoes/Converse/Chuck-Taylor-All-Star/1.jpg",
      "/shoes/Converse/Chuck-Taylor-All-Star/2.jpg",
      "/shoes/Converse/Chuck-Taylor-All-Star/3.jpg",
      "/shoes/Converse/Chuck-Taylor-All-Star/4.jpg",
    ],
    id: 25,
  },
  {
    name: "Chuck 70",
    price: 4299.0,
    description:
      "A premium version of the Chuck Taylor with upgraded materials and design.",
    availableSizes: ["5", "6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Converse",
    category: "Casual",
    images: [
      "/shoes/Converse/Chuck-70/0.jpg",
      "/shoes/Converse/Chuck-70/1.jpg",
      "/shoes/Converse/Chuck-70/2.jpg",
      "/shoes/Converse/Chuck-70/3.jpg",
      "/shoes/Converse/Chuck-70/4.jpg",
    ],
    id: 26,
  },
  {
    name: "Jordan Stadium 90",
    price: 7999.0,
    description:
      "A stylish and durable shoe designed for both performance and casual wear.",
    availableSizes: ["7", "8", "8.5", "9", "9.5", "10", "11", "12"],
    brand: "Nike",
    category: "Casual",
    images: [
      "/shoes/Nike/Jordan-Stadium-90/0.png",
      "/shoes/Nike/Jordan-Stadium-90/1.png",
      "/shoes/Nike/Jordan-Stadium-90/2.png",
      "/shoes/Nike/Jordan-Stadium-90/3.png",
      "/shoes/Nike/Jordan-Stadium-90/4.png",
    ],
    id: 27,
  },
  {
    name: "LeBron NXXT Gen AMPD EP",
    price: 8999.0,
    description:
      "High-performance basketball shoes with advanced cushioning and support.",
    availableSizes: ["7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Nike",
    category: "Basketball",
    images: [
      "/shoes/Nike/LeBron-NXXT-Gen-AMPD-EP/0.png",
      "/shoes/Nike/LeBron-NXXT-Gen-AMPD-EP/1.png",
      "/shoes/Nike/LeBron-NXXT-Gen-AMPD-EP/2.png",
      "/shoes/Nike/LeBron-NXXT-Gen-AMPD-EP/3.png",
      "/shoes/Nike/LeBron-NXXT-Gen-AMPD-EP/4.png",
    ],
    id: 28,
  },
  {
    name: "JA 1EP",
    price: 7999.0,
    description:
      "Signature shoes featuring sleek design and top-notch performance features.",
    availableSizes: ["7", "8", "8.5", "9", "9.5", "10", "11", "12"],
    brand: "Nike",
    category: "Basketball",
    images: [
      "/shoes/Nike/JA-1EP/0.png",
      "/shoes/Nike/JA-1EP/1.png",
      "/shoes/Nike/JA-1EP/2.png",
      "/shoes/Nike/JA-1EP/3.png",
      "/shoes/Nike/JA-1EP/4.jpg",
    ],
    id: 29,
  },
  {
    name: "Sabrina",
    price: 4999.0,
    description:
      "Stylish and versatile sneakers designed for comfort and daily wear.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Nike",
    category: "Casual",
    images: [
      "/shoes/Nike/Sabrina/0.jpg",
      "/shoes/Nike/Sabrina/1.png",
      "/shoes/Nike/Sabrina/2.jpg",
      "/shoes/Nike/Sabrina/3.jpg",
      "/shoes/Nike/Sabrina/4.jpg",
    ],
    id: 30,
  },
  {
    name: "Nike Precision 7",
    price: 4599.0,
    description:
      "Performance basketball shoes providing excellent grip and comfort on the court.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Nike",
    category: "Basketball",
    images: [
      "/shoes/Nike/Nike-Precision-7/0.png",
      "/shoes/Nike/Nike-Precision-7/1.png",
      "/shoes/Nike/Nike-Precision-7/2.png",
      "/shoes/Nike/Nike-Precision-7/3.png",
      "/shoes/Nike/Nike-Precision-7/4.jpg",
    ],
    id: 31,
  },
  {
    name: "Air Jordan 1 Mid SE",
    price: 5499.0,
    description:
      "A modern take on the classic Air Jordan 1 with updated materials and design.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Nike",
    category: "Casual",
    images: [
      "/shoes/Nike/Air-Jordan-1-Mid-SE/0.jpg",
      "/shoes/Nike/Air-Jordan-1-Mid-SE/1.jpg",
      "/shoes/Nike/Air-Jordan-1-Mid-SE/2.png",
      "/shoes/Nike/Air-Jordan-1-Mid-SE/3.png",
      "/shoes/Nike/Air-Jordan-1-Mid-SE/4.png",
    ],
    id: 32,
  },
  {
    name: "Nike SB Dunk Low Pro",
    price: 5999.0,
    description:
      "Classic SB Dunk Low sneakers with premium materials and unique design elements.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Nike",
    category: "Skate",
    images: [
      "/shoes/Nike/Nike-SB-Dunk-Low-Pro/0.png",
      "/shoes/Nike/Nike-SB-Dunk-Low-Pro/1.png",
      "/shoes/Nike/Nike-SB-Dunk-Low-Pro/2.png",
      "/shoes/Nike/Nike-SB-Dunk-Low-Pro/3.png",
      "/shoes/Nike/Nike-SB-Dunk-Low-Pro/4.png",
    ],
    id: 33,
  },
  {
    name: "Nike Pegasus 41 Electric",
    price: 7999.0,
    description:
      "High-performance running shoes with advanced cushioning and support for a smooth ride.",
    availableSizes: ["7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Nike",
    category: "Running",
    images: [
      "/shoes/Nike/Nike-Pegasus-41-Electric/0.png",
      "/shoes/Nike/Nike-Pegasus-41-Electric/1.png",
      "/shoes/Nike/Nike-Pegasus-41-Electric/2.png",
      "/shoes/Nike/Nike-Pegasus-41-Electric/3.png",
      "/shoes/Nike/Nike-Pegasus-41-Electric/4.png",
    ],
    id: 34,
  },
  {
    name: "Nike Air Force 1 '07 LV8",
    price: 5499.0,
    description:
      "A modern update on the iconic Air Force 1 with premium details and enhanced comfort.",
    availableSizes: ["6", "7", "8", "8.5", "9", "9.5", "10"],
    brand: "Nike",
    category: "Casual",
    images: [
      "/shoes/Nike/Nike-Air-Force-1-07-LV8/0.png",
      "/shoes/Nike/Nike-Air-Force-1-07-LV8/1.png",
      "/shoes/Nike/Nike-Air-Force-1-07-LV8/2.png",
      "/shoes/Nike/Nike-Air-Force-1-07-LV8/3.png",
      "/shoes/Nike/Nike-Air-Force-1-07-LV8/4.png",
    ],
    id: 35,
  },
  {
    name: "Air Jordan 4 Retro SE 'Wet Cement'",
    price: 10999.0,
    description:
      "Limited edition Air Jordan 4 with a retro design and unique 'Wet Cement' colorway.",
    availableSizes: ["7", "8", "8.5", "9", "9.5", "10", "11"],
    brand: "Nike",
    category: "Casual",
    images: [
      "/shoes/Nike/Air-Jordan-4-Retro-SE-Wet-Cement/0.jpg",
      "/shoes/Nike/Air-Jordan-4-Retro-SE-Wet-Cement/1.jpg",
      "/shoes/Nike/Air-Jordan-4-Retro-SE-Wet-Cement/2.jpg",
      "/shoes/Nike/Air-Jordan-4-Retro-SE-Wet-Cement/3.jpg",
      "/shoes/Nike/Air-Jordan-4-Retro-SE-Wet-Cement/4.png",
    ],
    id: 36,
  },
];

export const cartData = [
  {
    name: "Wayvee Leather",
    price: 4999.0,
    size: "7",
    brand: "Vans",

    image: "/shoes/Vans/Wayvee-Leather/0.webp",

    id: 1,
    quantity: 1,
  },
  {
    name: "Chukka Push",
    price: 4599.0,
    quantity: 1,
    size: "9",
    brand: "Vans",
    image: "/shoes/Vans/Chukka-Push/0.webp",
    id: 2,
  },
  {
    name: "Knu Skool",
    price: 4999.0,
    size: "11",
    brand: "Vans",

    image: "/shoes/Vans/Knu-Skool/0.webp",

    id: 3,
    quantity: 1,
  },
  {
    name: "Sport Low",
    price: 4399.0,
    size: "8.5",
    brand: "Vans",

    image: "/shoes/Vans/Sport-Low/0.webp",

    id: 4,
    quantity: 1,
  },
  {
    name: "Authentic",
    price: 3999.0,
    size: "9",
    brand: "Vans",

    image: "/shoes/Vans/Authentic/0.webp",
    quantity: 1,
    id: 5,
  },
];
